  <!--footer of the web site-->

  <!-- Footer section with contact and project link -->
  <footer>
    <p>Contact us at <a href="mailto:info@quantumtech.com.au">info@quantumtech.com.au</a></p>
    <p><a href="https://ibrahimmohamedirshadulhaq.atlassian.net/jira/software/projects/CWC/boards/34?selectedIssue=CWC-9&sprintStarted=true&atlOrigin=eyJpIjoiOWZlM2QwM2UzNDA1NGJjNzg4ZWRhYzE4NTFmODFhYzMiLCJwIjoiaiJ9">Jira Project Link</a></p>
  </footer>