 <!--header section of the web site-->
 <!-- Navigation Menu -->
 
  <header>
    <nav> <!-- Navigation bar-->
        <p class="menu"><a href="index.html">Home</a></p> <!-- Connnceted to index.html -->
		<p class="menu"><a href="jobs.html">Jobs</a> </p> <!-- Connected to jobs.html -->
		<p class="menu"><a href="apply.html">Apply</a></p> <!-- Connected to apply.html -->
		<p class="menu"><a href="about.html">About</a></p> <!-- Conncected to about.html-->
        <p class="menu"><a href="mailto:info@quantumtech.com.au">Email Us</a></p> <!-- Connected the email-->
    </nav>
  </header>