    <nav> <!-- Navigation bar-->
        <p class="menu"><a href="index.php">Home</a></p> <!-- Connnceted to index.php -->
		<p class="menu"><a href="jobs.php">Jobs</a> </p> <!-- Connected to jobs.php -->
		<p class="menu"><a href="apply.php">Apply</a></p> <!-- Connected to apply.php -->
		<p class="menu"><a href="about.php">About</a></p> <!-- Conncected to about.php-->
        <p class="menu"><a href="mailto:info@quantumtech.com.au">Email Us</a></p> <!-- Connected the email-->
    </nav>